Authorize user
jordanopensource/community-web pull request #160
Opened 2023-01-15 10:07 UTC by itsmohmans

2023-01-26 16:26 UTC, itsmohmans commented on components/login/Form.vue
> +  const {data: member} = await useFetch(`${config.public.COMMUNITY_API_URL}/auth/`)
To fix: session cookies are not sent with this request. See https://stackoverflow.com/a/5422323

2023-02-05 12:15 UTC, thamudi commented on middleware/auth.js
> +export default defineNuxtRouteMiddleware(async () => {
Add the route members/[id] to the list that checks if the user is auth or not. 
For the profile page, if the user is not authenticated just show the regular page without the edit page options.

2023-02-05 12:17 UTC, thamudi commented on components/login/Form.vue
> +    },
Redirect the auth member to the home page.

2023-02-05 12:22 UTC, thamudi commented on components/UserWidget.vue
> +  location.reload()
instead of reload, redirect the user to the homepage

2023-02-05 12:26 UTC, thamudi commented on server/api/forgot-password/send-email.post.js
> +    method: 'GET',
change this to a POST instead once the endpoint on the API is updated

2023-02-05 12:27 UTC, thamudi commented on pages/members/[id].vue
> +onMounted(() => {
Double check this file, it should already in the development, try rebasing

2023-02-05 12:29 UTC, thamudi requested changes
Please check the comments and update the branch accordingly

2023-02-06 11:46 UTC, thamudi approved these changes
Reviewed and approved

2023-02-06 13:02 UTC, merged